[build-system]
requires = ["setuptools>=80", "wheel", "setuptools-scm>=9"]
build-backend = "setuptools.build_meta"

[project]
name = "kizano"
dynamic = ["version"]
requires-python = ">=3.9"
dependencies = [
 "jira>=3.8.0",
 "PyYAML>=6.0.1",
]
authors = [
  {name = "Markizano Draconus", email = "markizano@markizano.net"},
]
maintainers = [
  {name = "Markizano Draconus", email = "markizano@markizano.net"},
]
description = "Kizano code for quick access to functions."
readme = "README.md"
license = "MIT"

classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]

[project.urls]
Homepage = "https://markizano.net"
Documentation = "https://docs.markizano.net"
Repository = "https://github.com/markizano/libkizano.py"
"Bug Tracker" = "https://github.com/markizano/libkizano.py/issues"
Changelog = "https://github.com/markizano/libkizano.py/blob/master/CHANGELOG.md"

[project.scripts]
log = "kizano.logger:syslogger"

[tool.setuptools_scm]
tag_regex = "^v(?P<version>.+)$"
version_scheme = "no-guess-dev"
local_scheme = "node-and-date"
write_to = "lib/kizano/_version.py"
write_to_template = "__version__ = \"{version}\"\n"

[tool.setuptools.package-dir]
mkzforge = "lib/kizano"

[tool.setuptools.packages.find]
where = ["lib"]
